### PR TITLE
order projects by status

### PR DESCRIPTION
**Pull request by C0rydoras**

### CODE REVIEW

**Review by anehx — COMMENTED** [review]
I don't really see what this is doing:

The PR title says you're sorting the projects by status. However, the code seems to be sorting projects by a computed property `endOfLife` which is just the EOL property of the first dependency of that project. How does this add any value?

**Comment by C0rydoras** [comment]
The status of a project is the status of its first dependency
https://github.com/adfinis/Outdated/blob/dea5f9d33e437aa41580a4340ff4ba32307c41b4/api/outdated/outdated/models.py#L109-L112

And the first dependency is always the most outdated one
https://github.com/adfinis/Outdated/blob/dea5f9d33e437aa41580a4340ff4ba32307c41b4/api/outdated/outdated/models.py#L72-L84

**Comment by anehx** [comment]
Then why aren't you sorting by the `status` property exposed by the backend?

**Comment by C0rydoras** [comment]
Because then i would have to implement some extra logic e.g.
```js
const statusOrder = {
  "OUTDATED": 0,
  "WARNING": 1,
  "UP-TO-DATE": 2,
  "UNDEFINED": 3,
};

projects.sort((a, b) => statusOrder[a.status] - statusOrder[b.status]);
```
And it would also not sort by the most outdated project

**Comment by anehx** [comment]
Okay, makes sense (the 2nd argument). Then let's do the ordering in the backend so you don't duplicate any logic. Or is there something that speaks against ordering in the backend in your opinion?

**Comment by C0rydoras** [comment]
As far as I know it is not really possible to order by an attribute of an m2m relationship e.g.
```python
     class Meta: 
         ordering = [ 
             "versioned_dependencies__release_version__end_of_life", 
         ] 
```
This does work but instead of the one project, we get the same project multiple times
image
image

Maybe this could be done on the `serializer`?

**Comment by anehx** [comment]
You can totally do that on the project view. You'll need to annotate the right property (most recent EOL of dependencies) and then order by it.

**Review by anehx — CHANGES_REQUESTED** [review]
LGTM, but this needs a test.

**Comment by C0rydoras** [comment]
Test added here: https://github.com/adfinis/Outdated/pull/55/commits/63bac9082f9f16027650d94ce5eb894f60e0fc3c

**Review by anehx — APPROVED** [review]

**Pull request merged**
