### PR TITLE
fix(api/tracking): ingore symlinks

### PR DESCRIPTION
**Pull request by c0rydoras**

### CODE REVIEW

**Review by open-dynaMIX — COMMENTED** [review]
Code looks good :+1:

What's the reasoning behind this? If I add a symlink to a `yarn.lock`-file to my repository, wouldn't I want it to be parsed too?

**Comment by c0rydoras** [comment]
It would then be parsed twice

**Comment by open-dynaMIX** [comment]
> It would then be parsed twice

Not if it points outside of the repo. You could handle duplicate files in another way and still providing this functionality. I admit, the use-cases for this are limited. But that's kinda the behaviour I would expect.

**Comment by c0rydoras** [comment]
It being able to point outside of the repo is a possible security issue. For example if I were to merge #228 now you could create a symlink in a repo to `/proc/1/environ` and dump db credentials, secret key etc.

**Comment by open-dynaMIX** [comment]
> It being able to point outside of the repo is a possible security issue.

You are absolutely right. It's early monday morning :sweat_smile:

**Review by open-dynaMIX — APPROVED** [review]
:+1:

**Pull request merged**
