### PR TITLE
chore(dependabot): group dependencies

### PR DESCRIPTION
**Pull request by c0rydoras**
make debendabot group dependencies

### CODE REVIEW

**Comment by anehx** [comment]
I think @derrabauke did something like that for our internal projects so it would make sense for him to review this.

**Comment by derrabauke** [comment]
I really like how you've grouped the packages. :+1: 

To align the automatic assignment of the reviewer with our other repos, it would be nice if you could add a [codeowners file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). I think it's more obvious than having a reviewer configured in a burried workflow definition.

**Comment by c0rydoras** [comment]
@derrabauke I have now added `CODEOWNERS` file and removed the reviewers from the dependabot config :)

**Review by derrabauke — APPROVED** [review]
:rocket:

**Pull request merged**
