### PR TITLE
ember: debug/log version of outdated

### PR DESCRIPTION
**Pull request by c0rydoras**
image

### CODE REVIEW

**Comment by anehx** [comment]
Why do you need this? Is the "Info > Libraries" tab in ember inspector not enough?

**Comment by c0rydoras** [comment]
I just want a quick way to check the version

**Comment by anehx** [comment]
> I just want a quick way to check the version

`debug` statements will be stripped from production builds so your solution would only work in development where I don't think the version is something you need to know as you'll be working from a branch, not a tag.

If you want to check the current version in production you can either use ember inspector or [`ember-cli-app-version`](https://github.com/ember-cli/ember-cli-app-version) to display it somewhere in the frontend.

**Comment by c0rydoras** [comment]
ah i didn't know that, thank you

ill make a PR for adding it to the frontend (#240)

**Comment by c0rydoras** [comment]
#242

**Pull request closed without merging**
